/* spalten.js — Spaltendefinition der SharePoint-Listen «Computer» und «Benutzer».
   Erzeugt aus code/schema-computer.json und code/schema-benutzer.json durch
   code/Build-Spalten.ps1 — nicht von Hand bearbeiten.

   i = interner Name in Graph, d = Anzeigename, t = Typ
   (Title|Text|Note|Boolean|Number|DateTime), g = Gruppe,
   q = Quelle: manuell = im Frontend bearbeitbar,
               sccm    = wird vom Sync aus SCCM überschrieben (schreibgeschützt),
               ad      = wird vom Sync aus dem Active Directory überschrieben (schreibgeschützt).

   Die Titelspalte heisst in Graph «Title»; sie wird in der Computer-Liste als «PC-Name»
   und in der Benutzer-Liste als «Login» angezeigt.

   Die Programmspalten der Benutzer-Liste stehen NICHT hier, sondern in programme.json
   (Ablage in SharePoint: Inventar/programme.json); modell.js ergänzt sie zur Laufzeit.
*/
const SPALTEN_COMPUTER = [
  { i: "Title", d: "PC-Name", t: "Title", g: "Stammdaten", q: "manuell" },
  { i: "Seriennummer", d: "Seriennummer", t: "Text", g: "Stammdaten", q: "manuell" },
  { i: "GebaeudeStock", d: "Gebäude / Stock", t: "Text", g: "Stammdaten", q: "manuell" },
  { i: "Bemerkung", d: "Bemerkung", t: "Note", g: "Stammdaten", q: "manuell" },
  { i: "Beschaffungsjahr", d: "Beschaffungsjahr", t: "Text", g: "Beschaffung", q: "manuell" },
  { i: "ErsatzGeplant", d: "Ersatz geplant", t: "Text", g: "Beschaffung", q: "manuell" },
  { i: "SCCM_Name", d: "SCCM Gerätename", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Found", d: "In SCCM vorhanden", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_ResourceID", d: "SCCM ResourceID", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_SMSID", d: "SCCM SMSID", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Domain", d: "Domäne", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_OU", d: "AD Distinguished Name", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_ADSite", d: "AD Standort", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_ADCreated", d: "AD Computerkonto erstellt", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_ADLastLogon", d: "AD letzte Anmeldung (Computerkonto)", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastLogonUser", d: "Letzter angemeldeter Benutzer", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_CurrentLogonUser", d: "Aktuell angemeldeter Benutzer", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_PrimaryUser", d: "Primärer Benutzer (SCCM)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_TopConsoleUser", d: "Hauptbenutzer (Konsolennutzung)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastConsoleUse", d: "Letzte Benutzeranmeldung", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_ConsoleUsers", d: "Konsolenbenutzer (Anmeldungen / Minuten / zuletzt)", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_ClientVersion", d: "SCCM Client-Version", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_ClientActive", d: "SCCM Client aktiv", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Online", d: "Online (SCCM)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastOnline", d: "Zuletzt online", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastOffline", d: "Zuletzt offline", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastActive", d: "Zuletzt aktiv (SCCM)", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastHardwareScan", d: "Letzter Hardware-Inventar", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastSoftwareScan", d: "Letzter Software-Inventar", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastDDR", d: "Letzter Heartbeat (DDR)", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastPolicyRequest", d: "Letzte Richtlinienanfrage", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastClientCheck", d: "Letzte Client-Prüfung", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_ClientCheckPass", d: "Client-Prüfung bestanden", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_ManagementPoint", d: "Management Point", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_BoundaryGroups", d: "Boundary Groups", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_CoManaged", d: "Co-Managed (Intune)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_AADDeviceID", d: "Entra Device ID", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Manufacturer", d: "Hersteller", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Model", d: "Modell", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_SerialNumber", d: "Seriennummer (SCCM)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_SMBIOSGUID", d: "SMBIOS GUID", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_ChassisType", d: "Gehäusetyp", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_IsVirtual", d: "Virtuelle Maschine", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_CPU", d: "Prozessor", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_CPUCores", d: "CPU Kerne", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_CPULogical", d: "CPU logische Prozessoren", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_RAMGB", d: "RAM (GB)", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_DiskCGB", d: "Laufwerk C: Grösse (GB)", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_DiskCFreeGB", d: "Laufwerk C: frei (GB)", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_PhysicalDisks", d: "Physische Datenträger", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_BIOSVersion", d: "BIOS-Version", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_BIOSDate", d: "BIOS-Datum", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_TPMVersion", d: "TPM-Version", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_TPMEnabled", d: "TPM aktiviert", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_BitLocker", d: "BitLocker", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Monitors", d: "Monitore", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_Battery", d: "Akku", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_OS", d: "Betriebssystem", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_OSVersion", d: "OS-Version (Build)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_OSInstallDate", d: "OS installiert am", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastBoot", d: "Letzter Neustart", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_OSLanguage", d: "OS-Sprache", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_SystemType", d: "Systemtyp", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_IPv4", d: "IPv4-Adresse", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_IPAddresses", d: "IP-Adressen (alle)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_MACAddresses", d: "MAC-Adressen", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_DHCP", d: "DHCP", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPEnabled", d: "Defender aktiv", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPClientVersion", d: "Defender Client-Version", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPSignatureVersion", d: "Defender Signaturversion", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPSignatureDate", d: "Defender Signaturdatum", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPLastQuickScan", d: "Defender letzter Schnellscan", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPLastFullScan", d: "Defender letzter Vollscan", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPInfectionStatus", d: "Defender Infektionsstatus", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPLastThreat", d: "Defender letzte Bedrohung", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPPendingReboot", d: "Defender Neustart ausstehend", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Office", d: "Office-Produkte", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_DeployedApps", d: "Zugewiesene Applikationen (Deployments)", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_AppsRequired", d: "Anzahl erforderliche Apps", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_AppsInstalled", d: "Anzahl installierte Apps (Deployments)", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_InstalledSoftware", d: "Installierte Software (Add/Remove)", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_InstalledSoftwareCount", d: "Anzahl installierte Software", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_Collections", d: "Sammlungen (Collections)", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastSync", d: "Letzte Synchronisation mit SCCM", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_SyncStatus", d: "Sync-Status", t: "Text", g: "SCCM", q: "sccm" }
];

const SPALTEN_BENUTZER = [
  { i: "Title", d: "Login", t: "Title", g: "Stammdaten", q: "ad" },
  { i: "Anzeigename", d: "Name", t: "Text", g: "Stammdaten", q: "ad" },
  { i: "EMail", d: "E-Mail", t: "Text", g: "Stammdaten", q: "ad" },
  { i: "Abteilung", d: "Abteilung", t: "Text", g: "Stammdaten", q: "ad" },
  { i: "Funktion", d: "Funktion", t: "Text", g: "Stammdaten", q: "ad" },
  { i: "Vorgesetzter", d: "Vorgesetzter", t: "Text", g: "Stammdaten", q: "ad" },
  { i: "Telefon", d: "Telefon", t: "Text", g: "Stammdaten", q: "ad" },
  { i: "Firma", d: "Firma", t: "Text", g: "Stammdaten", q: "ad" },
  { i: "ADAktiviert", d: "AD-Konto aktiv", t: "Text", g: "AD", q: "ad" },
  { i: "ADLetzterSync", d: "Letzter AD-Sync", t: "DateTime", g: "AD", q: "ad" },
  { i: "SCCMPrimaerGeraet", d: "Primärgerät (SCCM)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "Computer", d: "Computer", t: "Text", g: "Zuordnung", q: "manuell" },
  { i: "Bemerkung", d: "Bemerkung", t: "Note", g: "Zuordnung", q: "manuell" }
];
