/* spalten.js — Spaltendefinition der SharePoint-Liste «Computer Inventar».
   Erzeugt aus code/schema.json, nicht von Hand bearbeiten.
   i = interner Name in Graph, d = Anzeigename, t = Typ
   (Title|Text|Note|Boolean|Number|DateTime), g = Gruppe,
   q = Quelle (excel = aus der alten Excel-Liste, sccm = aus dem SCCM-Abgleich).
   Die Titelspalte heisst in Graph «Title» und wird als «PC-Name» angezeigt. */

const SPALTEN = [
  { i: "Arbeitsplatz", d: "Arbeitsplatz", t: "Text", g: "Stammdaten", q: "excel" },
  { i: "Login", d: "Login", t: "Text", g: "Stammdaten", q: "excel" },
  { i: "Firma", d: "Firma", t: "Text", g: "Stammdaten", q: "excel" },
  { i: "Bemerkung", d: "Bemerkung", t: "Note", g: "Stammdaten", q: "excel" },
  { i: "Title", d: "PC-Name", t: "Title", g: "Stammdaten", q: "excel" },
  { i: "Typ", d: "Typ", t: "Text", g: "Stammdaten", q: "excel" },
  { i: "Seriennummer", d: "Seriennummer", t: "Text", g: "Stammdaten", q: "excel" },
  { i: "TestuserSCCM", d: "Testuser SCCM", t: "Text", g: "Stammdaten", q: "excel" },
  { i: "GebaeudeStock", d: "Gebäude / Stock", t: "Text", g: "Stammdaten", q: "excel" },
  { i: "J20192020", d: "2019/2020", t: "Boolean", g: "Stammdaten", q: "excel" },
  { i: "J20202021", d: "2020/2021", t: "Boolean", g: "Stammdaten", q: "excel" },
  { i: "J20212022", d: "2021/2022", t: "Boolean", g: "Stammdaten", q: "excel" },
  { i: "J20222023", d: "2022/2023", t: "Boolean", g: "Stammdaten", q: "excel" },
  { i: "J20232024", d: "2023/2024", t: "Boolean", g: "Stammdaten", q: "excel" },
  { i: "J20242025", d: "2024/2025", t: "Boolean", g: "Stammdaten", q: "excel" },
  { i: "J20252026", d: "2025/2026", t: "Boolean", g: "Stammdaten", q: "excel" },
  { i: "Budget20262027", d: "Budget 2026/2027", t: "Boolean", g: "Budget", q: "excel" },
  { i: "Microsoft365", d: "Microsoft 365", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Project2019", d: "Project 2019", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Visio2019", d: "Visio 2019", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "SharePoint", d: "SharePoint", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "ZeitAG", d: "Zeit AG", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "TimePro", d: "Time.pro", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Presento", d: "Presento", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Projekto", d: "Projekto", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Dispo", d: "Dispo", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Exporto", d: "Exporto", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "PerformX", d: "PerformX", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "CampusAdmin", d: "Campus_Admin", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "CampusBenutzer", d: "Campus_Benutzer", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "CampusSchuladmin", d: "Campus_Schuladmin", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "RechtBearbeitungLogin", d: "Recht_Bearbeitung_Login", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "RechtBewertungen", d: "Recht_Bewertungen", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "RechtHonorar", d: "Recht_Honorar", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "RechtLohnDebi", d: "Recht_Lohn_Debi", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "RechtReferentenAdmin", d: "Recht_Referenten_Admin", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Protel", d: "Protel", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Bildung", d: "Bildung", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Direktion", d: "Direktion", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Sport", d: "Sport", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Finanzen", d: "Finanzen", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "HumanResources", d: "Human Resources", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "HWSSupport", d: "HWS/Support", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Infrastruktur", d: "Infrastruktur", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Lernende", d: "Lernende", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Manager", d: "Manager", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "MarKom", d: "MarKom", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Nachdienst", d: "Nachdienst", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Reception", d: "Reception", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Resto", d: "Resto", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "TechnischerDienst", d: "Technischer Dienst", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Veranstaltungen", d: "Veranstaltungen", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "PDFCreator", d: "PDFCreator", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "CitrixClient", d: "Citrix-Client", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "VLCPlayer", d: "VLC-Player", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "AdobeReader", d: "Adobe Reader", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "CAFMMeldeformular", d: "CAFM (Meldeformular)", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Frontify", d: "Frontify", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "KeePass", d: "KeePass", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "EvaSysCloud", d: "EvaSys Cloud", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Milestone", d: "Milestone", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Monocard", d: "Monocard", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "Wallboard", d: "Wallboard", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "AppCore", d: "AppCore", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "ABACUS", d: "ABACUS", t: "Boolean", g: "Standard-Software und Rechte", q: "excel" },
  { i: "AbaView", d: "AbaView", t: "Boolean", g: "ABACUS", q: "excel" },
  { i: "Administrator", d: "Administrator", t: "Boolean", g: "ABACUS", q: "excel" },
  { i: "Anlagenbuchhaltung", d: "Anlagenbuchhaltung", t: "Boolean", g: "ABACUS", q: "excel" },
  { i: "Debitorenbuchhaltung", d: "Debitorenbuchhaltung", t: "Boolean", g: "ABACUS", q: "excel" },
  { i: "Finanzbuchhaltung", d: "Finanzbuchhaltung", t: "Boolean", g: "ABACUS", q: "excel" },
  { i: "AbacusHumanResources", d: "Human Resources (ABACUS)", t: "Boolean", g: "ABACUS", q: "excel" },
  { i: "Kreditorenbuchhaltung", d: "Kreditorenbuchhaltung", t: "Boolean", g: "ABACUS", q: "excel" },
  { i: "Lohnbuchhaltung", d: "Lohnbuchhaltung", t: "Boolean", g: "ABACUS", q: "excel" },
  { i: "AdobeAcrobatPro", d: "Adobe Acrobat Pro", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "AdobeCreativeSuite", d: "Adobe Creative Suite", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "AttendantPro", d: "Attendant Pro", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "CADdyPP2D", d: "CADdy++ 2D", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "CADdyPP3D", d: "CADdy++ 3D", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "Microsoft365Copilot", d: "Microsoft 365 Copilot", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "MicrosoftPowerBIDesktop", d: "Microsoft Power BI Desktop", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "MicrosoftPowerBIProLizenz", d: "Microsoft Power BI Pro - Lizenz", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "PDFXChangeEditor", d: "PDF-XChange Editor", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "PrismaPrepare", d: "PrismaPrepare", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "Sunetplus", d: "Sunetplus", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "Supermailer", d: "Supermailer", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "TACReservationssystem", d: "TAC Reservationssystem", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "TCPOSAdmin", d: "TCPOS Admin", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "Silverlight", d: "Silverlight", t: "Boolean", g: "Zusatz-Software", q: "excel" },
  { i: "ADPhotoEdit", d: "AD Photo Edit", t: "Text", g: "Spezial-Software (AD-Gruppe)", q: "excel" },
  { i: "AdobePhotoshopCS6", d: "Adobe Photoshop CS6", t: "Text", g: "Spezial-Software (AD-Gruppe)", q: "excel" },
  { i: "ContentStudio", d: "Content Studio", t: "Text", g: "Spezial-Software (AD-Gruppe)", q: "excel" },
  { i: "Firefox", d: "Firefox", t: "Text", g: "Spezial-Software (AD-Gruppe)", q: "excel" },
  { i: "ForatableReservationsbuch", d: "Foratable Reservationsbuch", t: "Text", g: "Spezial-Software (AD-Gruppe)", q: "excel" },
  { i: "KeyMagic", d: "KeyMagic", t: "Text", g: "Spezial-Software (AD-Gruppe)", q: "excel" },
  { i: "PaulisKitchenSolution", d: "Paulis Kitchen Solution", t: "Text", g: "Spezial-Software (AD-Gruppe)", q: "excel" },
  { i: "PostPWC", d: "postPWC", t: "Text", g: "Spezial-Software (AD-Gruppe)", q: "excel" },
  { i: "Salto", d: "Salto", t: "Text", g: "Spezial-Software (AD-Gruppe)", q: "excel" },
  { i: "SupermailerADGruppe", d: "Supermailer (AD-Gruppe)", t: "Text", g: "Spezial-Software (AD-Gruppe)", q: "excel" },
  { i: "TACVista", d: "TAC Vista", t: "Text", g: "Spezial-Software (AD-Gruppe)", q: "excel" },
  { i: "Tiffany", d: "Tiffany", t: "Text", g: "Spezial-Software (AD-Gruppe)", q: "excel" },
  { i: "AutoCADLT", d: "AutoCAD LT", t: "Boolean", g: "Technik-Software", q: "excel" },
  { i: "ChauvinArnoux", d: "Chauvin Arnoux", t: "Boolean", g: "Technik-Software", q: "excel" },
  { i: "ELDESConfigTool", d: "ELDES Config Tool", t: "Boolean", g: "Technik-Software", q: "excel" },
  { i: "ETS6KNX", d: "ETS 6 (KNX)", t: "Boolean", g: "Technik-Software", q: "excel" },
  { i: "GateControl", d: "Gate Control", t: "Boolean", g: "Technik-Software", q: "excel" },
  { i: "SaltoPPDUSB", d: "Salto PPD USB", t: "Boolean", g: "Technik-Software", q: "excel" },
  { i: "SnapformViewer", d: "SnapformViewer", t: "Boolean", g: "Technik-Software", q: "excel" },
  { i: "Testo", d: "Testo", t: "Boolean", g: "Technik-Software", q: "excel" },
  { i: "Woehler", d: "Wöhler", t: "Boolean", g: "Technik-Software", q: "excel" },
  { i: "BpandaConsumer", d: "Bpanda Consumer", t: "Boolean", g: "Bpanda", q: "excel" },
  { i: "BpandaContributor", d: "Bpanda Contributor", t: "Boolean", g: "Bpanda", q: "excel" },
  { i: "BpandaManager", d: "Bpanda Manager", t: "Boolean", g: "Bpanda", q: "excel" },
  { i: "SCCM_Name", d: "SCCM Gerätename", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Found", d: "In SCCM vorhanden", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_ResourceID", d: "SCCM ResourceID", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_SMSID", d: "SCCM SMSID", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Domain", d: "Domäne", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_OU", d: "AD Distinguished Name", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_ADSite", d: "AD Standort", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_ADCreated", d: "AD Computerkonto erstellt", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_ADLastLogon", d: "AD letzte Anmeldung (Computerkonto)", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastLogonUser", d: "Letzter angemeldeter Benutzer", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_CurrentLogonUser", d: "Aktuell angemeldeter Benutzer", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_PrimaryUser", d: "Primärer Benutzer (SCCM)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_TopConsoleUser", d: "Hauptbenutzer (Konsolennutzung)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastConsoleUse", d: "Letzte Benutzeranmeldung", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_ConsoleUsers", d: "Konsolenbenutzer (Anmeldungen / Minuten / zuletzt)", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_ClientVersion", d: "SCCM Client-Version", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_ClientActive", d: "SCCM Client aktiv", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Online", d: "Online (SCCM)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastOnline", d: "Zuletzt online", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastOffline", d: "Zuletzt offline", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastActive", d: "Zuletzt aktiv (SCCM)", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastHardwareScan", d: "Letzter Hardware-Inventar", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastSoftwareScan", d: "Letzter Software-Inventar", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastDDR", d: "Letzter Heartbeat (DDR)", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastPolicyRequest", d: "Letzte Richtlinienanfrage", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastClientCheck", d: "Letzte Client-Prüfung", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_ClientCheckPass", d: "Client-Prüfung bestanden", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_ManagementPoint", d: "Management Point", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_BoundaryGroups", d: "Boundary Groups", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_CoManaged", d: "Co-Managed (Intune)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_AADDeviceID", d: "Entra Device ID", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Manufacturer", d: "Hersteller", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Model", d: "Modell", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_SerialNumber", d: "Seriennummer (SCCM)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_SMBIOSGUID", d: "SMBIOS GUID", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_ChassisType", d: "Gehäusetyp", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_IsVirtual", d: "Virtuelle Maschine", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_CPU", d: "Prozessor", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_CPUCores", d: "CPU Kerne", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_CPULogical", d: "CPU logische Prozessoren", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_RAMGB", d: "RAM (GB)", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_DiskCGB", d: "Laufwerk C: Grösse (GB)", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_DiskCFreeGB", d: "Laufwerk C: frei (GB)", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_PhysicalDisks", d: "Physische Datenträger", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_BIOSVersion", d: "BIOS-Version", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_BIOSDate", d: "BIOS-Datum", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_TPMVersion", d: "TPM-Version", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_TPMEnabled", d: "TPM aktiviert", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_BitLocker", d: "BitLocker", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Monitors", d: "Monitore", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_Battery", d: "Akku", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_OS", d: "Betriebssystem", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_OSVersion", d: "OS-Version (Build)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_OSInstallDate", d: "OS installiert am", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastBoot", d: "Letzter Neustart", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_OSLanguage", d: "OS-Sprache", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_SystemType", d: "Systemtyp", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_IPv4", d: "IPv4-Adresse", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_IPAddresses", d: "IP-Adressen (alle)", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_MACAddresses", d: "MAC-Adressen", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_DHCP", d: "DHCP", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPEnabled", d: "Defender aktiv", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPClientVersion", d: "Defender Client-Version", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPSignatureVersion", d: "Defender Signaturversion", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPSignatureDate", d: "Defender Signaturdatum", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPLastQuickScan", d: "Defender letzter Schnellscan", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPLastFullScan", d: "Defender letzter Vollscan", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPInfectionStatus", d: "Defender Infektionsstatus", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPLastThreat", d: "Defender letzte Bedrohung", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_EPPendingReboot", d: "Defender Neustart ausstehend", t: "Text", g: "SCCM", q: "sccm" },
  { i: "SCCM_Office", d: "Office-Produkte", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_DeployedApps", d: "Zugewiesene Applikationen (Deployments)", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_AppsRequired", d: "Anzahl erforderliche Apps", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_AppsInstalled", d: "Anzahl installierte Apps (Deployments)", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_InstalledSoftware", d: "Installierte Software (Add/Remove)", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_InstalledSoftwareCount", d: "Anzahl installierte Software", t: "Number", g: "SCCM", q: "sccm" },
  { i: "SCCM_Collections", d: "Sammlungen (Collections)", t: "Note", g: "SCCM", q: "sccm" },
  { i: "SCCM_LastSync", d: "Letzte Synchronisation mit SCCM", t: "DateTime", g: "SCCM", q: "sccm" },
  { i: "SCCM_SyncStatus", d: "Sync-Status", t: "Text", g: "SCCM", q: "sccm" }
];
